language: generic
sudo: required
services:
        - docker
before_install:
        - docker build -t tonyhong8/docker-react -f Dockerfile.dev . 
script:
        - docker run -e CI=true tonyhong8/docker-react npm run test 

deploy: 
        provider: elasticbeanstalk
        region: "us-east-1"
        app:  "docker-react3"
        env: "DockerReact3-env"
        bucket_name: "elasticbeanstalk-us-east-1-618248059406"
        bucket_path: "docker-react3" 
        on:
                branch: master
        access_key_id: "$AWS_ACCESS_KEY"
        secret_access_key: "$AWS_SECRET_KEY"

