sudo: required
services:
        - docker
before_install:
        - docker build -t tonyhong8/docker-react -f Dockerfile.dev . 
script:
        - docker run tonyhong8/docker-react npm run test -- --coverage


